### ISSUE TITLE
Log4Net logging on cloudwatch when the build is debug mode but it is logging in aws-logger-errors.txt in release mode.

### ISSUE THREAD

**Issue by ashishsingh92** [aws/aws-logging-dotnet#119]

**Comment by ashishsingh92** [comment]
Here is the code:

private void ConfigureLog4net()
        {   
            string convertionPattern = "%-4timestamp [%thread] %-5level %logger %ndc - %message%newline";

            string region = "us-east-1";

            string loggerAWSAccessKey = "myawsaccesskey";

            string loggerAWSSecretKey = "myawssecretkey";

            Hierarchy hierarchy = (Hierarchy)LogManager.GetRepository();
            PatternLayout patternLayout = new PatternLayout {ConversionPattern = convertionPattern};

            patternLayout.ActivateOptions();

            var appender = new AWSAppender
            {
                Layout = patternLayout,
                Credentials = new BasicAWSCredentials(loggerAWSAccessKey, loggerAWSSecretKey),
                LogGroup = ConfigurationManager.AppSettings["LogGroup"],
                Region = region
            };

            // Set log group and region. Assume credentials will be found using the default profile or IAM credentials.

            appender.ActivateOptions();
            hierarchy.Root.AddAppender(appender);

            hierarchy.Root.Level = Level.All;
            hierarchy.Configured = true;
        }

**Comment by ashishdhingra** [comment]
Hi @ashishsingh92,

Good afternoon.

I was going through the issue backlog and came across this issue. Unfortunately, I'm unable to reproduce the issue using the code below (from [samples](https://github.com/aws/aws-logging-dotnet/tree/master/samples/Log4net/ProgrammaticConfigurationExample)):

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using log4net;
using log4net.Repository.Hierarchy;
using log4net.Core;
using log4net.Appender;
using log4net.Layout;

using AWS.Logger.Log4net;
using System.Reflection;

namespace Log4NetTest
{
    class Program
    {
        static void Main(string[] args)
        {
            ConfigureLog4net();

            ILog log = LogManager.GetLogger(typeof(Program));
            log.Info("Check the AWS Console CloudWatch Logs console in us-east-1");
            log.Info("to see messages in the log streams for the");
            log.Info("log group Log4net.ProgrammaticConfigurationExample");

        }

        static void ConfigureLog4net()
        {
            Hierarchy hierarchy = (Hierarchy)LogManager.GetRepository(Assembly.GetEntryAssembly());
            PatternLayout patternLayout = new PatternLayout();

            patternLayout.ConversionPattern = "%-4timestamp [%thread] %-5level %logger %ndc - %message%newline";
            patternLayout.ActivateOptions();

            AWSAppender appender = new AWSAppender();
            appender.Layout = patternLayout;

            // Set log group and region. Assume credentials will be found using the default profile or IAM credentials.
            appender.LogGroup = "Log4net.ProgrammaticConfigurationExample";
            appender.Region = "us-east-1";

            appender.ActivateOptions();
            hierarchy.Root.AddAppender(appender);

            hierarchy.Root.Level = Level.All;
            hierarchy.Configured = true;
        }

    }
}
```

**.csproj file:**
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWS.Logger.Log4net" Version="1.5.2" />
  </ItemGroup>
</Project>
```

Executing the above code in Release mode, generated the log in CloudWatch successfully:
<img width="1210" alt="Screen Shot 2020-10-01 at 1 18 41 PM" src="https://user-images.githubusercontent.com/67916761/94858974-ac1fe700-03e8-11eb-9fdd-9be76fadaaee.png">


 I'm not sure about your project configuration since was per details on [aws-logging-dotnet](https://github.com/aws/aws-logging-dotnet) page, you can also configure logging in `log4net.config`, not sure if that might be conflicting with your programmatic configuration. Could you share your solution to troubleshoot the issue?

Since this issue is not reproducible, please confirm if this issue could be closed.

Thanks,
Ashish
