### ISSUE TITLE
Can we use Embedded Metric Format with Serilog AmazonCloudWatch

### ISSUE THREAD

**Issue by genifycom** [aws/aws-logging-dotnet#147]
We need to include the log-format header x-amzn-logs-format: json/emf along with the required JSON file to write Embedded Metric Format records to CloudWatch.

Is it possible to use the Serilog AWSCloudwatch sink to do this, or do we have to do this manually via PutLogEvents

**Comment by ashishdhingra** [comment]
Hi @genifycom,

Good morning.

I'm not sure if I get what is required by looking at the issue. Could you please elaborate more and preferably provide more details in the below format?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
@genifycom I thin you are referring to [Embedded Metric Format](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html). Per [Using the Client Libraries to Generate Embedded Metric Format Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Libraries.html), the libraries are available in Node.js, Python, and Java. I don't think this EMF format is supported out-of-box by Serilog extension for .NET.
