### ISSUE TITLE
Configure LogGroup expiration time via config file

### ISSUE THREAD

**Issue by spicoflorin** [aws/aws-logging-dotnet#157]
Hello!

We would like to configure the LogGroup expiration time from the configuration file of your libraries.
Can you please provide us an example on how to configure the expiration log time from a file?

  
We have seen that there was a feature request, but no update on that or any clear example on how to use it.
https://github.com/aws/aws-logging-dotnet/issues/55

We look forward for your guidance.

Thank you.

Regards,
  Florin

**Comment by ashishdhingra** [comment]
Hi @spicoflorin,

Good morning.

Thanks for posting the guidance question. As pointer out in issue #55 and based on code analysis, I do not see any option to configure log expiration time for the generated CloudWatch logs. However you can use the [AWSSDK.CloudWatchLogs](https://www.nuget.org/packages/AWSSDK.CloudWatchLogs/) package's [AmazonCloudWatchLogsClient.PutRetentionPolicy()](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html) method to add a retention policy of an existing log group. Hope this helps.

If required, you may add `feature-request` label (and remove `guidance` label) so that this option is added in future version of library.

Thanks,
Ashish
