### ISSUE TITLE
AWSLoggerConfig with AssumeRoleAWSCredentials expires after 3600 seconds

### ISSUE THREAD

**Issue by Venkatachalapatee** [aws/aws-logging-dotnet#173]
The process is configuring the Serilog AwsSink with AssumeRoleAWSCredentials,  AssumeRoleAWSCredentials default expiration is 3600 seconds, After the expiration, the Role Credentials are not refreshed, This causes the process not to log to Cloud Watch.

**Comment by ashishdhingra** [comment]
Hi @Venkatachalapatee,

Could you please share the issue details along with sample code to reproduce the issue in the below issue template format along with logs?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by Venkatachalapatee** [comment]
Using the AssumeRoleAWSCredentials solved the problem, Closing the issue.
