### ISSUE TITLE
Unable to create an IAM policy that uses a specific log group ARN

### ISSUE THREAD

**Issue by avolcoff** [aws/aws-logging-dotnet#179]
This is the deepest IAM policy Resource path I could create that works with your logging library:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:GetLogEvents",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:PutRetentionPolicy"
            ],
            "Resource": "arn:aws:logs:<region>:<account-number>:log-group:*"
        }
    ]
}
```

this is not good as it allows applications to create any log group that they want...
can you assist?

**Comment by avolcoff** [comment]
by using the environment variable "Logging__LogStreamNamePrefix" - I was able to get a bit deeper in the path - but still, I cannot name the log-group or log-stream - can you assist?
"Resource": "arn:aws:logs:<region>:<account-number>:log-group:*:log-stream:*"

**Comment by ashishdhingra** [comment]
Hi @avolcoff,

Good morning.

Thanks for posting guidance question.

Upon investigating, as [Readme](https://github.com/aws/aws-logging-dotnet#required-iam-permissions) specifies, regardless of the framework used, the following permissions must be allowed (via IAM) for the provided AWS credentials:
```
logs:CreateLogGroup
logs:CreateLogStream
logs:PutLogEvents
logs:DescribeLogGroups
```
The logging library would attempt to create the log group with the specified name if it doesn't already exist as per [LogEventTransmissionSetup()](https://github.com/aws/aws-logging-dotnet/blob/5411f0495a18e0cdc344ef87e5cccad2cca567aa/src/AWS.Logger.Core/Core/AWSLoggerCore.cs#L468) code. You should be able to restrict the IAM policy to a particular log group, refer **Example 3: Allow access to one log group** at [Using identity-based policies (IAM policies) for CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-identity-based-access-control-cwl.html). 

The log stream name(s) are auto-generated, refer the logic for [GenerateStreamName()](https://github.com/aws/aws-logging-dotnet/blob/5411f0495a18e0cdc344ef87e5cccad2cca567aa/src/AWS.Logger.Core/Core/AWSLoggerCore.cs#L497) which always includes a unique date-based segment. So it's unclear if you would be able to constrain IAM policy to a particular log stream.

Hope this helps.

Thanks,
Ashish

**Comment by avolcoff** [comment]
This explanation is really nice but does not work on aws.
Could you show me an example of an iam policy that is restricted to a
specific log group that actually works for you?

**Comment by ashishdhingra** [comment]
> This explanation is really nice but does not work on aws. Could you show me an example of an iam policy that is restricted to a specific log group that actually works for you?

@avolcoff Looks like I'm able to find root cause on why IAM policy which specifies the specific log group ARN doesn't work with the logging libraries. For reproduction, used the following steps:
- Created a log group `testloggroup` in CloudWatch logs.
- Created a new IAM policy named `testloggingpolicy` with the following permissions:
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:DescribeLogGroups",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:<<region>>:<<account_id>>:log-group:testloggroup:*"
        }
    ]
}
```
Notice that I have set the `Resource` to the ARN of log group.
- Created a new IAM user named `testloguser` with programmatic access generating access key id and secret key.
- Configured the access key id and secret key in the `default` profile in credentials profile chain (for Windows, located at `%User_Directory%/.aws/credentials`).
- Opened Fiddler.
- Used and ran code sample at https://github.com/aws/aws-logging-dotnet/tree/master/samples/Serilog/SerilogTestCodeFromConfig with the specific log group configuration and region.
- Examined CloudWatch logs. **RESULT:** Log stream not created.
- Examined Fiddler logs. **RESULT:** There are failed attempts for `DescribeLogGroupss` service operation.

Upon further investigation, looks like [LogEventTransmissionSetup()](https://github.com/aws/aws-logging-dotnet/blob/5411f0495a18e0cdc344ef87e5cccad2cca567aa/src/AWS.Logger.Core/Core/AWSLoggerCore.cs#L457) is trying to describe log groups if the log group creation is not disabled in config. IAM policy also lists that specific log group resource would not work for certain operations (e.g. DescribeLogGroups). This validates the fact that we cannot constrain IAM policy to specific log group if log group creation is not disabled (tested it by changing resource in IAM policy to `arn:aws:logs:*:<<account_id>>:log-group:*`.

For further validation, I disabled the log group creation using configuration setting `DisableLogGroupCreation` as `true`:
```JSON
{
  "Serilog": {
    "Using": [
      "AWS.Logger.SeriLog"
    ],
    "LogGroup": "testloggroup",
    "Region": "us-east-2",
    "DisableLogGroupCreation": true,
    "MinimumLevel": "Information",
    "WriteTo": [
      {
        "Name": "AWSSeriLog"
      }
    ]
  }
}
```

Using the above IAM policy to constrain to specific log group now works. Hope this helps.

**Comment by avolcoff** [comment]
Thanks Ashish,
We are using the  AWS.Logger.AspNetCore
<https://www.nuget.org/packages/AWS.Logger.AspNetCore/> library, and not
the Serilog library
Will it still work?

**Comment by ashishdhingra** [comment]
> Thanks Ashish, We are using the AWS.Logger.AspNetCore <https://www.nuget.org/packages/AWS.Logger.AspNetCore/> library, and not the Serilog library Will it still work?

@avolcoff All logging frameworks in this repository share the common library. The above workaround should work for `AWS.Logger.AspNetCore` package as well. The configuration should look something like below:
```JSON
"Logging": {
  "Region": "us-east-2",
  "LogGroup": "AspNetCore.WebSample",
  "DisableLogGroupCreation": true,
  "IncludeLogLevel": true,
  "IncludeCategory": true,
  "IncludeNewline": true,
  "IncludeException": true,
  "IncludeEventId": false,
  "IncludeScopes": false,
  "LogLevel": {
    "Default": "Debug",
    "System": "Information",
    "Microsoft": "Information"
  }
}
```

Since you already have the working solution, please give it a try.

Thanks,
Ashish

**Comment by avolcoff** [comment]
Your solution is working - Thanks Ashish!!
