### ISSUE TITLE
web service running in elastic beanstalk is not logging entries to cloudwatch

### ISSUE THREAD

**Issue by yalba** [aws/aws-logging-dotnet#30]
I have a web server running in Elastic Beanstalk. I configured NLog to log application messages to CloudWatch. When I run the web server locally in localhost (which uses my default credentials), I see the messages from my app logged to CloudWatch. However, when I deploy to Elastic Beanstalk and execute a post request, there is no entry in cloudwatch. What am I missing. The ec2 isntance running the web app uses an IAM role which access policy includes: 
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups"
Any idea what am I missing?

**Comment by normj** [comment]
That looks like the right permissions. Is your application using any other AWS SDKs and are they successful?

**Comment by scrappydog** [comment]
I'm seeing this same behavior... ElasticBeanstalk, AspNet Core 2.0 website, using aws-logging-dotnet directly (no Nlog or Log4net)... works fine in locally... only creates the log group running on EC2

**Comment by scrappydog** [comment]
FIXED: By supplying correct AWS Key and Secret as Environment variables in ElasticBeanstalk Configuration.

**Comment by bzuillsmith** [comment]
I am having the same issue. I cannot get my ELB instance to send logs to CloudWatch. I'm not sure what I'm missing. From what I understand, I shouldn't need to specify any AWS Key or Secret; it just works based off the instance profile, right?

My instance profile (IAM role) includes the Managed Policy `AWSElasticBeanstalkWebTier` which contains

```json
        {
            "Sid": "CloudWatchLogsAccess",
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:*:*:log-group:/aws/elasticbeanstalk*"
            ]
        }
```

My `LogGroup` property in appsettings is similar to `/aws/elasticbeanstalk/MyApp/Staging/Logs` which should be allowed according to the Resource section of the policy above. The group was manually created since there is no `logs:CreateLogGroup` action on the policy.

My code in my ASP.NET Core app during Startup is:
```c#
    LoggerFactory.AddAWSProvider(Configuration.GetAWSLoggingConfigSection());
    var logger = LoggerFactory.CreateLogger<Startup>();       
    logger.LogInformation("Doing something...");
```

ELB automatically created a few cloudwatch groups. 2 of them have logs: .../IIS-Log and .../EBDeploy-Log

The app runs. I can go to pages in the app which means there are no exceptions during startup. The problem is I can't tell if *anything* related to AWS is working in the app because I can't get these logs to work. The typical stdout logs don't seem to be accessible in ELB for a .NET Core app according to AWS documentation. I don't know how to debug these logging issues without logging... any ideas of what to try next?

**Comment by yalba** [comment]
I fixed my issue a few days after I posted the question, and I forgot to come back and update it.
I think I fixed it by adding a few more permissions to the instance IAM role, see below for what I am including, add the missing ones and try again. Good luck!

            "Sid": "CloudWatchAppLogsAccess",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:GetLogEvents",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:PutRetentionPolicy"
            ],

**Comment by bzuillsmith** [comment]
Got it working. My issue was a spelling error that caused the JSON config file with the AWS.Logging config section to not be loaded, and it was set to optional. My fault. I was starting to figure it wasn't anything to do with this library because no one else was reporting the issue. Thanks!
