### ISSUE TITLE
Log Entires Not Showing for App running in ECS Container 

### ISSUE THREAD

**Issue by ejohn20** [aws/aws-logging-dotnet#31]
I have added some basic logging statements to an application. See below for details. This works fine debugging locally. However, when pushing the app out to AWS, building a container in CodeBuild, and running the container on an ECS instance, the entries do not show up. I have other calls to AWS APIs running in the container OK (e.g. SES and SSM).

```JSON
"AWS.Logging": {
    "Region": "us-west-2",
    "LogGroup": "/app/portal/production",
    "LogLevel": {
      "Default": "Information",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  },
```

```c#
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, MyDbContext dbContext)
{
   //Configure cloudwatch logging
   loggerFactory.AddAWSProvider(Configuration.GetAWSLoggingConfigSection());
   var logger = loggerFactory.CreateLogger<Program>();
   logger.LogInformation(LoggingEvents.ApplicationStart, "Application configuration start");
}
```

Instance profile policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "ssm:GetParameter",
                "ses:SendEmail",
                "ses:SendRawEmail"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

Any ideas on why this would show up in dev and not in release mode running in the container?

**Comment by scrappydog** [comment]
bump

**Comment by ejohn20** [comment]
I have this working now as well. It was an error in my policy above. Apparently, this is not enough:

"logs:CreateLogGroup",
"logs:CreateLogStream",
"logs:PutLogEvents",
"logs:DescribeLogStreams",

I have not found the hardened policy that will allow this to work without logs:* as the policy yet. I'll circle back.

**Comment by rbwestmoreland** [comment]
@ejohn20 I found the following policy to work:

logs:CreateLogGroup
logs:CreateLogStream
logs:PutLogEvents
logs:DescribeLogGroups

**Comment by ejohn20** [comment]
Interesting, this must be something unique in my environment. I'm also seeing logging work for a short period of time and then randomly stop working. I have to redeploy the container in order for it to start working again. Something is off, but I haven't pinned down the issue yet.

**Comment by akotranza** [comment]
@ejohn20 I read your thread before making a new issue report, but not closely enough maybe because this sounds potentially similar to what we are experiencing -- though we are not running in ECS:
 [https://github.com/aws/aws-logging-dotnet/issues/34](url). 

An example from our case, a deploy on Jan 3rd of an asp net core 2.0 app w/ 2 EC2 instances logged until Jan 5th, while another app deployed the same day (w/ same code base) w/ 6 EC2 instances logged until Jan 9th. In both cases the apps are under constant (but not taxing) load. I've seen the same issue w/ a different aspnet core web app running a single instance.

The only "fix" seems to be to redeploy the app. The log group targeted by the app then creates new log streams and accepts logs once again, but only for a few more days.

I'm left wondering if there is a limit or competition issue resulting from the default configuration of this package. We had dotnet core 1.0 apps use v1.0.0 of this package without running into this issue. AWS forums claim no active issues w/ CloudWatch Logs, so 🤔

**Comment by ejohn20** [comment]
Closing this issue, as I think the root problem is covered in @akotranza's new issue #34 .
