### ISSUE TITLE
NLog not sending logs to CloudWatch

### ISSUE THREAD

**Issue by ntrivix** [aws/aws-logging-dotnet#35]
NLog not sending logs to CloudWatch

Target frameword
```<TargetFramework>netcoreapp1.0</TargetFramework>```

Packages
```
<PackageReference Include="AWS.Logger.Core" Version="1.1.4" />
<PackageReference Include="AWS.Logger.NLog" Version="1.1.4" />
<PackageReference Include="NLog" Version="5.0.0-beta07" />
<PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
<PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.1.0" />
<PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="1.0.1" />
...
```

NLog.config
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true"
      internalLogToConsole="true"
      internalLogLevel="Trace">
  <extensions> <add assembly="NLog.AWS.Logger" /> </extensions>
  <targets>
    
    <target name="awsout" type="AWSTarget" logGroup="critical-errors" region="eu-central-1"> 
      <layout xsi:type="JsonLayout" includeAllProperties="true"> 
        <attribute name="time" layout="${longdate}" /> 
        <attribute name="level" layout="${level:upperCase=true}"/> 
        <attribute name="message" layout="${message}" encode="false" /> 
        <attribute name="stack-trace" layout="${stacktrace:format=Raw:topFrames=5}"/> 
      </layout> 
    </target>
    </targets>
  <rules>
    <logger name="CriticalErrors" minlevel="Info" writeTo="awsout" />
  </rules>
</nlog>
```

Code
```
Logger Logger = LogManager.GetLogger("CriticalErrors");
Logger.Error(() => JsonConvert.SerializeObject(new Dictionary<string, object>
            {
                {"UNKNOWN-ERROR", internalError.GetLogCode()},
                {"ERROR-TYPE", "UNKNOWN"},
                {"PAYLOAD", stackTrace}
            }));
```

What am I doing wrong?

**Comment by jsolman** [comment]
eu-central-1 is not working for me either.

**Comment by karanrn** [comment]
I am using NLog for us-east-1 in Lambda function. When load testing is done on the Lamdba, NLog doesn't write logs to Cloudwatch. If 1000 messages are sent, it only logs for few of the requests.
And logs are logged after processing of few requests not immediate ( I tried out changing buffer size).
Am I missing something?

**Comment by frankyjuang** [comment]
same here. any updates?

**Comment by karanrn** [comment]
No, We are planning to change from NLog to some other framework.

**Comment by normj** [comment]
@karanrn These libraries are not a great fit for Lambda because the send the messages to CloudWatch Logs in a background thread but Lambda can freeze or recycle the compute environment before that background thread gets a chance to write the messages. I would recommend either using the ILambdaContext logging API or [Amazon.Lambda.Logging.AspNetCore](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore) which are integrated with the CloudWatch Log assigned to the Lambda function and doesn't have the background thread issue.

**Comment by karanrn** [comment]
Thank you @normj, we will try out Amazon.Lambda.Logging.AspNetCore logging

**Comment by snakefoot** [comment]
Have tried to improve on this with  #53

**Comment by daymansiege** [comment]
@normj, does it make sense to use NLog in Lambda at all if we have such problems with async events flushing?

**Comment by karanrn** [comment]
I am using Microsoft.Extensions.Logging. Underlying I am using Console.WriteLine(), but it lighter and quick. It does give all the flexibility needed.

**Comment by snakefoot** [comment]
Make sure to use the same region for cloudwatch as for the container (or else credential handshake will often fail and nothing is transmitted).

If using Lambda then it makes much better sense to write directly to console, and then configure CloudWatch for the Lambda-console-output. You can consider using NLog for generating JSON-output to the console if you want structured logging.

New release is available that improves flush to CloudWatch: https://www.nuget.org/packages/AWS.Logger.NLog/1.3.1

**Comment by sginige** [comment]
Doesn't work from `ap-southeast-2` either.  Worked ok from `us-east-1` :thinkroll:

**Comment by clearwaterstream** [comment]
> 
> 
> @karanrn These libraries are not a great fit for Lambda because the send the messages to CloudWatch Logs in a background thread but Lambda can freeze or recycle the compute environment before that background thread gets a chance to write the messages. I would recommend either using the ILambdaContext logging API or [Amazon.Lambda.Logging.AspNetCore](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore) which are integrated with the CloudWatch Log assigned to the Lambda function and doesn't have the background thread issue.

I'm having the same issue, logs are not sent to CloudWatch from my ASP.NET Core App hosted out of Lambda. The log group + stream does get created, but no entries. After spending some time on it I just switched to "Console" as the target. Whatever is sent to the console ends up showing up in CloudWatch. I'm using JsonLayout to render the elements, and I was pleasantly surprised to see CloudWatch Insights picking up my custom json fields. Splunk like -- nice! I'll prob switch to Amazon.Lambda.Logging.AspNetCore logging b/c it's possible console logs are scrubbed and pumped to CloudWatch in async fashion (by some sort of output stream reader). This may create disjointed logs from the console + the existing ASP.NET Core logs that get auto-magically pumped to CloudWatch w/o me having to do any configuration.

**Comment by amitabhb** [comment]
> @karanrn These libraries are not a great fit for Lambda because the send the messages to CloudWatch Logs in a background thread but Lambda can freeze or recycle the compute environment before that background thread gets a chance to write the messages. I would recommend either using the ILambdaContext logging API or Amazon.Lambda.Logging.AspNetCore which are integrated with the CloudWatch Log assigned to the Lambda function and doesn't have the background thread issue.

Hi @normj thanks but, I agree the default logger in the context works great. But as per my company I would have to use NLog or Log4Net, I have tried to implement NLog as well as Log4Net with the example provided in AWS.Logger.Nlog etc... while processing a million record from a S3 Bucket and using NLog or Log4Net to log cerain information, it doesn't log everything. The C# code uses a Lambda and it's using a combination of Async and Parallel.Foreach . Can you suggest what I am missing (I feel there is a thread issue... but works fine with ILambdaLogger) , or it's not the correct approach ?

**Comment by snakefoot** [comment]
You can setup NLog at runtime to write output to AWS ILogger:


https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-cloud-logging-with-Azure-function-or-AWS-lambda#writing-to-ilambdacontext-ilambdalogger-in-aws


Sent from my Sony Xperia


---- amitabhb wrote ----


@karanrn<https://github.com/karanrn> These libraries are not a great fit for Lambda because the send the messages to CloudWatch Logs in a background thread but Lambda can freeze or recycle the compute environment before that background thread gets a chance to write the messages. I would recommend either using the ILambdaContext logging API or Amazon.Lambda.Logging.AspNetCore which are integrated with the CloudWatch Log assigned to the Lambda function and doesn't have the background thread issue.

Hi @normj<https://github.com/normj> thanks but, I agree the default logger in the context works great. But as per my company I would have to use NLog or Log4Net, I have tried to implement NLog as well as Log4Net with the example provided in AWS.Logger.Nlog etc... while processing a million record from a S3 Bucket and using NLog or Log4Net to log cerain information, it doesn't log everything. The C# code uses a Lambda and it's using a combination of Async and Parallel.Foreach . Can you suggest what I am missing (I feel there is a thread issue... but works fine with ILambdaLogger) , or it's not the correct approach ?

**Comment by jstallm** [comment]
@normj , You mentioned previously that nlog was not necessarily "a great fit for Lambda"
Does this still apply today?

**Comment by normj** [comment]
Still true. They rely on a background task to push to CloudWatch logs and there isn't a mechanism right now to force a flush of the background queue before Lambda event is completed and the process is frozen.

**Comment by jstallm** [comment]
@normj , not saying your not right in any way, clearly you know what your talking about. 

But I have to ask: Why would AWS say 
_"The supported .NET logging frameworks are NLog, Log4net, and the new built-in ASP.NET Core logging Framework. For each framework, all you need to do is add the appropriate NuGet package, add CloudWatch Logs as an output source, and then use your logging library as you normally would_."

https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/cw-log-frameworks.html

**Comment by normj** [comment]
Thanks for pointing the docs out. They are wrong and I will contact the doc writer to get it updated.

**Comment by jstallm** [comment]
@normj , thank you. Your going above and beyond the call of duty for sure. :)

Where else can we find documented support that NLog is not to be used with Lambda? (besides this thread, of course)
In other words, if a chief architect of enterprise fortune 500 company asks me to use NLog for Lambda, and I tell them its not supported, is this thread the best reference for this? What else can I provide them without having to of course go through and fail using NLog within a lambda? What supportive documentation can I use?

**Comment by normj** [comment]
It does say in the README for this repo that these libraries are not recommended for Lambda
https://github.com/aws/aws-logging-dotnet#aws-lambda

**Comment by jstallm** [comment]
@normj , Does it say it explicitly? or is it implied? I dont see it explicity in that readme. Thank you by the way for helping us here.

**Comment by ashishdhingra** [comment]
Hi @ntrivix,

Good morning.

I was going through the issue backlog and came across this guidance question. As @norm pointed to Readme https://github.com/aws/aws-logging-dotnet#aws-lambda, there is a note mentioning that NLog might not be suitable for use with Lambda since NLog sends and processes messages in background thread. The background thread will be frozen once a Lambda event is processed and may not ever be unfrozen if more Lambda events are not received for some time. Hence, with Lambda, it is recommended to use either the ILambdaContext.Logger.LogLine or the [Amazon.Lambda.Logging.AspNetCore](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore) package.

Please let me know if this issue could be closed.

Thanks,
Ashish

**Comment by jstallm** [comment]
I think https://aws.amazon.com/blogs/developer/amazon-cloudwatch-logs-and-net-logging-frameworks/ needs to be updated with a concise description that lambdas shouldnt use NLog to help the next person avoid encountering this problem. Murphy's law.

**Comment by ashishdhingra** [comment]
@jstallm Thats a developer blog, not sure how it could be updated. Documentation (Readme) should be pointed out for any reference. But thanks for pointing out.

**Comment by jstallm** [comment]
@ashishdhingra , It doesnt matter how old the developer blog is because the reality is developers still read the blog, and people will still be waiting valuable engineering time until either the blog is updated, or removed. Developers end up on that blog post when searching.

**Comment by jstallm** [comment]
Where can I request this blog be updated? I really strongly recommend this as I hear even within my organization/enterprise confusion regarding the use of NLog within lambdas. There are many teams actually using NLog within lamdbas with no idea of this issue. The right thing to do is to place this detail within the blog. If the blog is still worth reading, and keeping, its worth updating.

**Comment by ashishdhingra** [comment]
@jstallm I'm not sure how frequently the developer blogs are updated, specially when it dates back to more than 3 years. However, the documentation and Readme are usually kept up to date. For requesting an update to developer blog, a new issue with label "documentation" could be opened, which could be discussed with the developer.

**Comment by clearwaterstream** [comment]
@jstallm @ashishdhingra 

Sometimes these blog entries do pop up via Google search, and I've personally have learned over the years to keep an eye on the posted date, as things do change. Not everyone may do so and indeed some engineering effort may we wasted.

I've added a comment to the blog, the comments need to be approved. Can we at the very least approve the comment so that if someone happens to read the comments section they can get a warning there (quick win). Updating the blog itself would be a better solution.

**Comment by ashishdhingra** [comment]
@jstallm @clearwaterstream Thanks for the update. I will take a note of this and discuss with developer to review the comment on the blog https://aws.amazon.com/blogs/developer/amazon-cloudwatch-logs-and-net-logging-frameworks/.

**Comment by snakefoot** [comment]
If going to update the blog-post, then please update the Nlog.config example to include:

```xml
  <extensions>
    <add assembly="NLog.AWS.Logger" />
  </extensions>
```

Like this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  throwConfigExceptions="true">
  <extensions>
    <add assembly="NLog.AWS.Logger" />
  </extensions>
  <targets>
    <target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample" region="us-east-1"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="aws" />
  </rules>
</nlog>
```

**Comment by jstallm** [comment]
@snakefoot , this github issue is scoped to issue with using nlog with lambda and the thread freezing issue .

**Comment by normj** [comment]
@clearwaterstream I don't have permission to approve the comments but I update the blog post with the same comment from the README file about how these libraries don't work well for Lambda.

**Comment by ashishdhingra** [comment]
@clearwaterstream The blog post is updated to include a note about logging with Lambda. Hence closing this issue.
