### ISSUE TITLE
Quick tool becomes slow due to AWSLoggerCore.Close() call in finalizer

### ISSUE THREAD

**Issue by roa-nyx** [aws/aws-logging-dotnet#61]
We were recently investigating some performance issues with our in-house tooling, specifically a strange pause between completing all processing and a few seconds where nothing appears to be happening before our tool releases control back to the command line.

After some troubleshooting we ran dotTrace, to try to see what was happening. A call was logged by the Finalizer for about 1 and a half seconds to AWSLoggerCore.Close().

We tried to call this explicitly but have not found anyway to expose the AWSLoggerCore class instance so that we can call the function ourselves. Is there some way to reach it? If not, shouldn't there be a way so that we can manage it's closing when we desire it and provide messaging to the user like `Closing AWSLoggerCore...`.

Any help would be greatly appreciated. I can't do a minimal reproducible case right now, but will try to get around to it at some point tomorrow if you're having trouble reproducing this issue.

**Comment by klaytaybai** [comment]
Hi @klick-barakgall, thank you for your feedback on this.  Could you please describe the severity of the impact this is having on your business?

**Comment by klick-barakgall** [comment]
We have a tool that needs to be called repeatedly. The tool's payload takes a fraction of a second to complete. However tasks that rely on it being called dozens of times, now take minutes instead of seconds.

We've disabled AWS logging for this tool for now, but we worry that this will come back to bite us later.

I would caution against marking this as a feature request, maybe it's just me but I feel that this is a blocking issue that will make it impossible for devs to rely on this toolset in various applications.

A fix would need to:
A) resolve why AWSLoggerCore.Close is taking close to 1.5 seconds. I assume it's verifying that all log messages have been sent or something along these lines? Maybe there is a better way to do this? Offload the check to another process, or else allow the developer to pre-empt this behaviour in some way?
B) (optionally) make it safe to call `.Close` multiple times and expose it so developers can manage the lifecycle of logging within their own applications.

If you disagree I would love to hear your thoughts on this @klaytaybai.

**Comment by snakefoot** [comment]
@klick-barakgall Would you be willing to try a custom build based on the code from PR #53 :

https://github.com/aws/aws-logging-dotnet/issues/56#issuecomment-440819512 (PreRelease Nuget-packages to put in local nuget repository)

**Comment by snakefoot** [comment]
@klick-barakgall New release is available that improves flush to CloudWatch: https://www.nuget.org/packages/AWS.Logger.NLog/1.3.1

**Comment by klick-barakgall** [comment]
That's amazing! We'll give it a try soon. Apologies for not responding to your previous request. I had intended to get back to you but time slipped away from me. I appreciate the follow through!

**Comment by normj** [comment]
Indeed, thanks @snakefoot for your contributions!

**Comment by chazt3n** [comment]
Any luck @roa-nyx ?

**Comment by roa-nyx** [comment]
I'm sorry all, I can't find the code segment that we used to log using NLog. I feel like maybe we found another solution in the meantime and I won't be able to come up with a minimal case to test this.
