### ISSUE TITLE
What are the minimum permissions required when log group is already created

### ISSUE THREAD

**Issue by yahya99223** [aws/aws-logging-dotnet#62]
Hello, 
What are the minimum permissions required when log group is already created?
it is mentioned [here](https://aws.amazon.com/blogs/developer/amazon-cloudwatch-logs-and-net-logging-frameworks/) that I need the following:
"logs:CreateLogGroup",
"logs:CreateLogStream",
"logs:PutLogEvents",
"logs:DescribeLogGroups"
but since the group is already created, I expect that:
"logs:CreateLogStream",
"logs:PutLogEvents" 
should be enough, tried that but I do n't see any streams logged, any guidance?

**Comment by klaytaybai** [comment]
@yahya99223, sorry for not getting to this sooner.  I'm going to be spending more time helping the team support and maintain this repo going forward.  Use of this repo requires DescribeLogGroups and CreateLogGroup because we always check to see if the configured log group already exists and create it if it doesn't.  I'll add these permission requirements to the README.

Changing this behavior would result in a breaking change for customers, so we will keep it as is by default.  If you are for some reason unable to use these permissions, please let us know so we can consider this a feature request to add an additional configuration that could skip the log group code.
