### ISSUE TITLE
The AWS Logger in-memory buffer has reached maximum capacity

### ISSUE THREAD

**Issue by ksks88** [aws/aws-logging-dotnet#73]
We get this error in production after a day or so of logs (and no more logs after that): 
[aws-error.txt](https://github.com/aws/aws-logging-dotnet/files/2876135/aws-error.txt).

Our setup looks like this:
Program.cs: 

```
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
                 WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) =>
                {
#if !DEBUG
                    logging.AddProvider(new AWSLoggerProvider(hostingContext.Configuration.GetAWSLoggingConfigSection("AWS"),
                formatter: (logLevel, message, exception) => $"[{DateTime.UtcNow}] {logLevel}: {message} \n {exception}"));
#endif

                })
                .ConfigureServices(services =>
                {
                    services.AddTransient<IStartupFilter, HangfireStartupFilter>();
                })
                .UseStartup<Startup>()
                .UseSetting("detailedErrors", "true")
                .CaptureStartupErrors(true)
                .UseUrls("http://0.0.0.0:5000");
```
Note, our logging filter is not under AWS node in appsettings.json, but it filter just fine:
```
"Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Warning"
    }
  },
  "AWS": {
    "Profile": "aws-profile",
    "Region": "us-east-1",
    "LogGroup": "Production",
    ...
  },
```
App is running under .net core 2.1.7 runtime and we are using AWS.Logger.AspNetCore 1.4.1.

**Comment by klaytaybai** [comment]
@ksks88, I think the most helpful thing for you would be to identify a remedy for your connection issues.  I'm guessing you are using the default MaxQueuedMessages value of 10000 instead of specifying something lower in the configuration, correct?   Your messages will keep piling up into a queue until they  are sent out.  For some reason, your connection is broken.

Is the profile you are using able to access CloudWatch 24/7?  (i.e. Is it using temporary credentials?)
Is the code running on a device with a reliable network?

Let's start brainstorming

**Comment by ksks88** [comment]
Hey @klaytaybai, thanks for help. We are hosting our app in docker container on ECS service, so I'm not sure how connection could be problem, however we are using one IAM user (profile) for all environments (QA, STG and Prod) could this be a problem?

**Comment by pcoulter** [comment]
I'm having the same issue.  I get "Operation canceled", and then about 3 hours later, I get "The AWS Logger in-memory buffer has reached maximum capacity" message.  If I reboot the VM in EC2, then the logs start sending again.  It seems that something gets hung up when the operation is canceled in SendMessages, and it never attempts to resend.  I'm guessing that I get a single connection failure, and then no new connection attempts are made.  It should attempt to resend after the next push interval.

**Comment by pcoulter** [comment]
Confirmed: If I explictly throw a System.Threading.Tasks.TaskCanceledException from inside SendMessages, then the OperationCanceledException ex catch block inside Monitor() is invoked, and the client is disposed.  Perhaps some sort of retry logic would be appropriate, as it's not unlikely for the AWS endpoint to drop a connection occasionally.

**Comment by bitshop** [comment]
Another customer w/ issue. Using default value, ECS, task profile - All standard stuff. Takes down prod .net core application at scale.

**Comment by dimmy-timmy** [comment]
I'm having the same issue. 
nlog appender got error
`TaskCanceledException making request PutLogEventsRequest to https://logs.eu-west-1.amazonaws.com/. Attempt 1 --> System.Threading.Tasks.TaskCanceledException: The operation aws cancelled ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled`
and then
 `System.InvalidOperationException: The AWS Logger in-memory buffer has reached maximum capacity` 
after few hours.

The issue is here, message dequeue loop just breaks on exception in `SendMessages`
https://github.com/aws/aws-logging-dotnet/blob/master/src/AWS.Logger.Core/Core/AWSLoggerCore.cs#L369

Definitely need some retry or requeue  logic, or at least throw terminating exception.
