### ISSUE TITLE
Lambdas going cold cause missed Cloudwatch Log writes

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-logging-dotnet#91]
What this impacts
-------------------
I'm using log4net and this library but I suspect this happens with all the providers that use AWSCoreLogger and are deployed to a Lambda.

What's happening
---------------------
I noticed that sometimes I'm not getting Cloudwatch logs from some of my Lambda invocations. This seems to especially happen when the Lambda executes very fast. 

I am able to get some Cloudwatch logs written out but only when the function executes for a long time OR the function is being invoked quickly so it doesn't go cold.

Also, even if the Lambda runs for a long time I think it's still not logging out the last log entries if the Lambda goes cold and never restarts.

Where I suspect the problem is
---------------------------
You have a batching/delay operator that only submits the Cloudwatch logs every X seconds to Cloudwatch. 

But if a Lambda doesn't run for long enough to submit based on the time restriction then the Lambda appears to get paused and never calls the AWSLoggerCore.ProcessExit() function. 

This means the log entries never get written out. 

How I figured this out
-------------------------
I pulled down this library and added Console.WriteLine statements all thru the code in AWSLoggerCore and changed the MonitorSleepTime from 500ms to 1 second. Below is a screenshot where I have highlighted each of the log statements I'm writing out to the console. 

![image](https://user-images.githubusercontent.com/1039795/60389818-b46ad300-9a7d-11e9-928c-4776a7d7a66b.png)

Here is part of the **Monitor()** function where some of those messages are coming from
![image](https://user-images.githubusercontent.com/1039795/60389852-44a91800-9a7e-11e9-86a9-0acd0dda3e4c.png)

**SendMessages()** when called logs as well but you notice those are missing in the screenshot
![image](https://user-images.githubusercontent.com/1039795/60389861-791cd400-9a7e-11e9-878f-99d30c7128c5.png)

What it looks like if the Lamda stays active
------------------------------
Here is a screenshot of what it looks like if the Lambda stays active with requests. Notice how it is sending messages. I got this to work by invoking the Lambda quickly over and over again so AWSLoggerCore could run it's **Monitor()** check.

![image](https://user-images.githubusercontent.com/1039795/60389882-314a7c80-9a7f-11e9-9bb5-45b2301df010.png)

**Comment by PaulDMendoza** [comment]
My temporary workaround for my quick jobs is to shorten the BatchPushInterval to 200ms. This should push up to 5 times per second which is the limit. Then for the jobs at least I add a 1 second delay before the exit. Still haven't figured out how to add a delay to the shutdown sequence for ASP.NET Core when running in a Lambda to achieve the same thing.

**Comment by normj** [comment]
These libraries don't work well in Lambda because as you have seen they rely on messages being sent to CloudWatch in a background thread. Since the background thread will be frozen as soon as there is not a lambda event to process, there is no guarantee the process will be reawaken to send what ever messages have been queued up in the in memory cache.

Log4net has no concept of a flush that you could invoke at the end of your event processing. NLog does have a flush mechanism that you can call.

If you really want to use Log4net in Lambda you would be better off using the console appender which Lambda will capture all of the std out and send it to the log stream that Lambda assigned to the function.

We do have a comment in the [README](https://github.com/aws/aws-logging-dotnet#aws-lambda) for the repo about these libraries not being well suited for Lambda. You are not the only one that I have heard attempting to use these libraries in Lambda though. Is there something more we can do to make it clear not to use these in lambda case? Also I would be curious to know if there are any use cases that using the console appender in Lambda does not handle.

**Comment by PaulDMendoza** [comment]
Dang, I missed that comment in the readme. 

Yeah, I guess just using the console output from Lambdas is what I have to do. It's kind of a pain though because searching events that span Lambdas is a pain like this. I like sending all my logs for an environment to one bucket and then I can easily filter across Lamdbas.
